# Generated by Django 5.1.1 on 2024-09-11 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'City',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Country',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'District',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Beneficiary'},
        ),
        migrations.AlterModelOptions(
            name='cashassigned',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Cash Bank'},
        ),
        migrations.AlterModelOptions(
            name='changingroom',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Changing Room'},
        ),
        migrations.AlterModelOptions(
            name='changingroomassign',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Changing Room Allocation'},
        ),
        migrations.AlterModelOptions(
            name='greenhouseroom',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Green House Room'},
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Cash Repayment'},
        ),
        migrations.AlterModelOptions(
            name='storeroom',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Store Room'},
        ),
        migrations.AlterModelOptions(
            name='storeroomassign',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Store Room Allocation'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Supervisor'},
        ),
        migrations.AlterModelOptions(
            name='trendknowledgebank',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Trend Knowledge Bank'},
        ),
        migrations.AlterModelOptions(
            name='trendknowledgediscussion',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Trend Knowledge Discussion'},
        ),
        migrations.AlterModelOptions(
            name='watertank',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Water Reservoir'},
        ),
        migrations.RemoveField(
            model_name='trendknowledgebank',
            name='content',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashassigned',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changingroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changingroomassign',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greenhouseroom',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeroomassign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trendknowledgebank',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watertank',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.city'),
        ),
        migrations.AddField(
            model_name='watertank',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.district'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.country')),
            ],
            options={
                'verbose_name_plural': 'Region',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.region'),
        ),
    ]
