# Generated by Django 5.1.1 on 2024-09-11 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0003_beneficiary_active_beneficiary_assigned_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhouseroom',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='assigned_tunnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='yuapp.greenhouseroom'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enterprise Name'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='city',
            field=models.ManyToManyField(blank=True, to='yuapp.city'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='greenhouse',
            field=models.ManyToManyField(blank=True, to='yuapp.greenhouse'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='nationalId',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport Picture'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport Picture'),
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='crops',
            field=models.ManyToManyField(blank=True, to='yuapp.crop'),
        ),
        migrations.CreateModel(
            name='MarketingCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Market Center',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='marketing_centres',
            field=models.ManyToManyField(blank=True, to='yuapp.marketingcentre'),
        ),
        migrations.CreateModel(
            name='WorkerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_worker_role_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Beneficiary Woker Role',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport Picture')),
                ('nationalId', models.TextField(blank=True, max_length=15, null=True)),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='yuapp.beneficiary')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_worker_created', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.workerrole')),
            ],
            options={
                'verbose_name_plural': 'Beneficiary Wokers',
                'ordering': ['-created_at'],
            },
        ),
    ]
