# Generated by Django 5.1.1 on 2024-09-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0006_alter_supervisor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='nationalId',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='Ghana Card'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='nationalId',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='Ghana Card'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='nationalId',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='Ghana Card'),
        ),
    ]
