# Generated by Django 5.1.1 on 2024-09-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0009_maintenance_photo_repayment_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='cardphoto',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiary/photos/', verbose_name='Ghana Card Picture'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='cardphoto',
            field=models.ImageField(blank=True, null=True, upload_to='worker/photos/', verbose_name='Ghana Card Picture'),
        ),
        migrations.AddField(
            model_name='worker',
            name='cardphoto',
            field=models.ImageField(blank=True, null=True, upload_to='worker/photos/', verbose_name='Ghana Card Picture'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='nationalId',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ghana Card'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='nationalId',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ghana Card'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='nationalId',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ghana Card'),
        ),
    ]
