# Generated by Django 5.1.1 on 2024-09-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0012_alter_greenhouseroom_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.city', verbose_name='City'),
        ),
    ]
