# Generated by Django 5.1.1 on 2024-09-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0014_marketingcentre_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='changingroom',
            name='greenhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='green_house', to='yuapp.greenhouse'),
        ),
        migrations.AddField(
            model_name='storeroom',
            name='greenhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greenhouse', to='yuapp.greenhouse'),
        ),
    ]
