# Generated by Django 5.1.1 on 2024-09-13 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0017_remove_beneficiary_assigned_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='nationalId',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Ghana Card'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='nationalId',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Ghana Card'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='yuapp.beneficiary'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worker',
            name='nationalId',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Ghana Card'),
        ),
    ]
