# Generated by Django 5.1.1 on 2024-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0019_alter_worker_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
