# Generated by Django 5.1.1 on 2024-09-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0021_supervisor_user_alter_supervisor_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendknowledgediscussion',
            name='tagged_beneficiaries',
            field=models.ManyToManyField(blank=True, related_name='discussions', to='yuapp.beneficiary'),
        ),
    ]
