# Generated by Django 5.1.1 on 2024-09-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0022_trendknowledgediscussion_tagged_beneficiaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='cardphoto',
            field=models.ImageField(blank=True, null=True, upload_to='edo/photos/', verbose_name='Ghana Card Picture'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='edo/photos/', verbose_name='Passport Picture'),
        ),
    ]
