# Generated by Django 5.1.1 on 2024-09-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0025_grade_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
