# Generated by Django 5.1.1 on 2024-09-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0026_harvest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='confirmation',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Not Confirmed', 'Not Confirmed')], max_length=20, null=True),
        ),
    ]
