# Generated by Django 5.1.1 on 2024-10-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0028_alter_harvest_options_productunit_harvest_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Crop Production Unit'},
        ),
    ]
