# Generated by Django 5.1.1 on 2024-10-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0029_alter_productunit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='expression',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Measuring Unit'),
        ),
    ]
