# Generated by Django 5.1.1 on 2024-10-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0031_alter_harvest_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.productunit'),
        ),
    ]
