# Generated by Django 5.1.1 on 2024-10-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0033_aic_transaction_payment_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Delivery'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Purchase Payment'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Transaction'},
        ),
    ]
