# Generated by Django 5.1.1 on 2024-10-02 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0036_order_orderitem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='active',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='harvest_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.harvest'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_ordered',
            field=models.PositiveIntegerField(),
        ),
    ]
