# Generated by Django 5.1.1 on 2024-10-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0038_order_created_at_order_created_by_order_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
