# Generated by Django 5.1.1 on 2024-10-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0039_orderitem_active_orderitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_items',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
