# Generated by Django 5.1.1 on 2024-10-03 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0041_pricetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='market_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_center_price', to='yuapp.marketingcentre'),
        ),
    ]
