# Generated by Django 5.1.1 on 2024-10-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0042_pricetable_market_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
