# Generated by Django 5.1.1 on 2024-10-07 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0043_pricetable_selling_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('contract_type', models.CharField(choices=[('Temporary', 'Temporary'), ('Permanent', 'Permanent'), ('Casual', 'Casual')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('charge_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='yuapp.beneficiary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='yuapp.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
