# Generated by Django 5.1.1 on 2024-10-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0044_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_mode_type',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], max_length=50, null=True),
        ),
    ]
