# Generated by Django 5.1.1 on 2024-10-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0045_contract_payment_mode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_mode_type',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=50, null=True),
        ),
    ]
