# Generated by Django 5.1.1 on 2024-10-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0046_alter_contract_payment_mode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Ended', 'Ended'), ('Terminated', 'Terminated')], default='Active', max_length=20),
        ),
    ]
