# Generated by Django 5.1.1 on 2024-10-14 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0047_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='price_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuapp.pricetable'),
        ),
    ]
