# Generated by Django 5.1.1 on 2024-10-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0048_harvest_price_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='confirmation',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Closed', 'Closed'), ('Not Confirmed', 'Not Confirmed')], max_length=20, null=True),
        ),
    ]
