# Generated by Django 5.1.1 on 2024-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0049_alter_harvest_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='total_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
