# Generated by Django 5.1.1 on 2024-10-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0050_harvest_total_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='total_sales',
            new_name='total_price',
        ),
    ]
