# Generated by Django 5.1.1 on 2024-10-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0051_rename_total_sales_harvest_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='price_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.pricetable'),
        ),
    ]
