# Generated by Django 5.1.1 on 2024-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0053_alter_harvest_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='confirmation',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Closed', 'Closed'), ('Open', 'Open')], default='Open', max_length=20),
        ),
    ]
