# Generated by Django 5.1.1 on 2024-10-18 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0054_alter_harvest_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_harvest', to='yuapp.beneficiary'),
        ),
    ]
