# Generated by Django 5.1.1 on 2024-10-18 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0055_alter_harvest_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='assigned_tunnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_tunnel', to='yuapp.greenhouseroom'),
        ),
    ]
