# Generated by Django 5.1.1 on 2024-10-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0056_alter_beneficiary_assigned_tunnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouseroom',
            name='assinged',
            field=models.IntegerField(default=0),
        ),
    ]
