# Generated by Django 5.1.1 on 2024-10-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0057_greenhouseroom_assinged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenhouseroom',
            old_name='assinged',
            new_name='assign',
        ),
    ]
