# Generated by Django 5.1.1 on 2024-10-19 00:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0058_rename_assinged_greenhouseroom_assign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInputCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='farminput/category/photos/', verbose_name='Upload Photo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Farm Input Category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InputDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contactperson', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='farminput/dealer/photos/', verbose_name='Upload Photo')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Farm Input Dealer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity_received', models.IntegerField(default=0)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='farminput/photos/', verbose_name='Upload Photo')),
                ('confirmation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirm_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_farm_inputs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_farm_inputs', to=settings.AUTH_USER_MODEL)),
                ('inputcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.farminputcategory')),
                ('inputdealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.inputdealer')),
            ],
            options={
                'verbose_name_plural': 'Farm Input Receivable',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InputDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distribution_date', models.DateField(auto_now_add=True)),
                ('confirmation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary')),
                ('confirm_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_distributions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_distributions', to=settings.AUTH_USER_MODEL)),
                ('distributed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.supervisor')),
                ('farm_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.farminput')),
            ],
            options={
                'verbose_name_plural': 'Farm Input Distribution',
                'ordering': ['-created_at'],
            },
        ),
    ]
