# Generated by Django 5.1.1 on 2024-10-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0059_farminputcategory_inputdealer_farminput_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farminput',
            name='name',
        ),
    ]
