# Generated by Django 5.1.1 on 2024-10-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0060_remove_farminput_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdealer',
            name='cost_per_unit',
        ),
    ]
