# Generated by Django 5.1.1 on 2024-10-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0061_remove_inputdealer_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
