# Generated by Django 5.1.1 on 2024-10-21 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0062_buyer_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Crop Harvest Records'},
        ),
        migrations.AddField(
            model_name='harvest',
            name='greenhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='greenhouse_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouseroom'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='confirmation',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Closed', 'Closed'), ('Open', 'Open'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='HeightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('average_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse')),
                ('greenhouse_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouseroom')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heightdata_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_irrigated', models.DateField()),
                ('water_quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('method', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse')),
                ('greenhouse_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouseroom')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigationdata_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NurseryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planted', models.DateField()),
                ('seeds_sown', models.IntegerField()),
                ('seeds_germinated', models.IntegerField()),
                ('seedlings_transplanted', models.IntegerField()),
                ('avg_germination_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_survival_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse')),
                ('greenhouse_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouseroom')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurserydata_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SprayingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sprayed', models.DateField()),
                ('chemical_used', models.CharField(max_length=100)),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse')),
                ('greenhouse_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouseroom')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprayingdata_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrellisingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_trellised', models.DateField()),
                ('method', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse')),
                ('greenhouse_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouseroom')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trellisingdata_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
