# Generated by Django 5.1.1 on 2024-10-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0063_alter_harvest_options_harvest_greenhouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurserydata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
