# Generated by Django 5.1.1 on 2024-10-23 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0064_nurserydata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heightdata',
            name='measurement_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='irrigationdata',
            name='date_irrigated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nurserydata',
            name='date_planted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trellisingdata',
            name='date_trellised',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
