# Generated by Django 5.1.1 on 2024-10-23 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0065_alter_heightdata_measurement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heightdata',
            name='crops',
            field=models.ManyToManyField(blank=True, to='yuapp.crop'),
        ),
        migrations.AddField(
            model_name='irrigationdata',
            name='crops',
            field=models.ManyToManyField(blank=True, to='yuapp.crop'),
        ),
        migrations.AddField(
            model_name='nurserydata',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.crop'),
        ),
        migrations.AddField(
            model_name='sprayingdata',
            name='crops',
            field=models.ManyToManyField(blank=True, to='yuapp.crop'),
        ),
        migrations.AddField(
            model_name='trellisingdata',
            name='crops',
            field=models.ManyToManyField(blank=True, to='yuapp.crop'),
        ),
    ]
