# Generated by Django 5.1.1 on 2024-10-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0066_heightdata_crops_irrigationdata_crops_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trellisingdata',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='heightdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprayingdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
