# Generated by Django 5.1.1 on 2024-10-24 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0067_rename_notes_trellisingdata_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heightdata',
            name='crops',
        ),
        migrations.RemoveField(
            model_name='irrigationdata',
            name='crops',
        ),
        migrations.RemoveField(
            model_name='sprayingdata',
            name='crops',
        ),
        migrations.RemoveField(
            model_name='trellisingdata',
            name='crops',
        ),
        migrations.AddField(
            model_name='heightdata',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.crop'),
        ),
        migrations.AddField(
            model_name='irrigationdata',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.crop'),
        ),
        migrations.AddField(
            model_name='sprayingdata',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.crop'),
        ),
        migrations.AddField(
            model_name='trellisingdata',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.crop'),
        ),
    ]
