# Generated by Django 5.1.1 on 2024-10-24 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0068_remove_heightdata_crops_remove_irrigationdata_crops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprayingdata',
            name='date_sprayed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
