# Generated by Django 5.1.1 on 2024-10-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0069_alter_sprayingdata_date_sprayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationdata',
            name='area_covered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
