# Generated by Django 5.1.1 on 2024-11-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0071_remove_delivery_transaction_remove_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='harvest_record',
            new_name='harvest',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity_ordered',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
