# Generated by Django 5.1.1 on 2024-11-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0075_delivery_confirm_at_delivery_confirm_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='confirmation_note',
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
