# Generated by Django 5.1.1 on 2024-11-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0076_remove_delivery_confirmation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='quantity_received',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
