# Generated by Django 5.1.1 on 2024-11-16 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0077_delivery_quantity_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
