# Generated by Django 5.1.1 on 2024-11-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0078_delivery_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='quantity_received',
            new_name='quantity_receive',
        ),
    ]
