# Generated by Django 5.1.1 on 2024-12-01 05:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0080_remove_payment_transaction_remove_transaction_crop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputEdoDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distribution_date', models.DateField(auto_now_add=True)),
                ('confirmation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirm_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_edo_distributions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_edo_distributions', to=settings.AUTH_USER_MODEL)),
                ('distributed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.aic')),
                ('farm_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.farminput')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.supervisor')),
            ],
            options={
                'verbose_name_plural': 'Farm Input Edo Distribution',
                'ordering': ['-created_at'],
            },
        ),
    ]
