# Generated by Django 5.1.1 on 2024-12-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0082_alter_inputdistribution_farm_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdistribution',
            name='farm_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edo_distributions', to='yuapp.farminput'),
        ),
        migrations.AlterField(
            model_name='inputedodistribution',
            name='farm_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aic_distributions', to='yuapp.farminput'),
        ),
    ]
