# Generated by Django 5.1.1 on 2024-12-01 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0083_alter_inputdistribution_farm_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputedodistribution',
            name='farm_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.farminput'),
        ),
    ]
