# Generated by Django 5.1.1 on 2024-12-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0084_alter_inputedodistribution_farm_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdistribution',
            old_name='distributed_by',
            new_name='distributed_by_edo',
        ),
    ]
