# Generated by Django 5.1.1 on 2024-12-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0085_rename_distributed_by_inputdistribution_distributed_by_edo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdistribution',
            old_name='distributed_by_edo',
            new_name='distributed_by',
        ),
    ]
