# Generated by Django 5.1.1 on 2024-12-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0086_rename_distributed_by_edo_inputdistribution_distributed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdistribution',
            name='farm_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edo_distributions', to='yuapp.inputedodistribution'),
        ),
    ]
