# Generated by Django 5.1.1 on 2024-12-12 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0087_alter_inputdistribution_farm_input'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputdistribution',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Farm Input Distribution - Beneficiaries'},
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='yuapp.transaction'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='yuapp.buyer'),
        ),
    ]
