# Generated by Django 5.1.1 on 2024-12-27 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0090_irrigationdata_finishtime_irrigationdata_starttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='expected_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
