# Generated by Django 5.1.1 on 2024-12-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0091_todo_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='days_left',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
