# Generated by Django 5.1.1 on 2024-12-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0092_todo_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='days_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
