# Generated by Django 5.1.1 on 2024-12-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0093_alter_todo_days_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_latitude', models.FloatField()),
                ('login_longitude', models.FloatField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.supervisor')),
            ],
        ),
    ]
