# Generated by Django 5.1.1 on 2024-12-29 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0094_supervisorattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprayingdata',
            name='sprayed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.worker'),
        ),
    ]
