# Generated by Django 5.1.1 on 2024-12-31 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0095_sprayingdata_sprayed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprayingdata',
            old_name='sprayingMethos',
            new_name='sprayingMethod',
        ),
    ]
