# Generated by Django 5.1.1 on 2024-12-31 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0096_rename_sprayingmethos_sprayingdata_sprayingmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprayingdata',
            name='sprayingMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.sprayingmedthod'),
        ),
    ]
