# Generated by Django 5.1.1 on 2025-01-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0097_alter_sprayingdata_sprayingmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprayingdata',
            name='finishTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprayingdata',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
