# Generated by Django 5.1.1 on 2025-01-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0098_alter_sprayingdata_finishtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationdata',
            name='finishTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='irrigationdata',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
