# Generated by Django 5.1.1 on 2025-01-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0099_alter_irrigationdata_finishtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
