# Generated by Django 5.1.1 on 2025-02-09 23:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0100_alter_harvest_quantity_alter_harvest_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancecost',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='maintenancecost',
            name='applies_to_all',
            field=models.BooleanField(default=False, help_text='Check if this applies to all beneficiaries'),
        ),
        migrations.AddField(
            model_name='maintenancecost',
            name='beneficiary',
            field=models.ForeignKey(blank=True, help_text='Leave empty if this is a general cost', null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary'),
        ),
        migrations.AddField(
            model_name='maintenancecost',
            name='greenhouse',
            field=models.ForeignKey(blank=True, help_text='If empty, this cost is not specific to a greenhouse', null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse'),
        ),
        migrations.AlterField(
            model_name='cashassigned',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashloans', to='yuapp.beneficiary'),
        ),
        migrations.AlterField(
            model_name='maintenancecost',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='BillableCostItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('applies_to_all', models.BooleanField(default=True, help_text='Check if this applies to all beneficiaries')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='billablecostitems/photos/', verbose_name='Upload Photo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('greenhouse', models.ForeignKey(blank=True, help_text='If empty, this cost applies to all greenhouses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greenhouse_billables', to='yuapp.greenhouse')),
            ],
            options={
                'verbose_name_plural': 'Billable Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='maintenancecost',
            name='billable_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.billablecostitems'),
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
