# Generated by Django 5.1.1 on 2025-02-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0101_remove_maintenancecost_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancecost',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary'),
        ),
        migrations.AlterField(
            model_name='maintenancecost',
            name='greenhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse'),
        ),
    ]
