# Generated by Django 5.1.1 on 2025-02-10 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0102_alter_maintenancecost_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecost',
            name='date_validTo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
