# Generated by Django 5.1.1 on 2025-02-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0103_maintenancecost_date_validto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancecost',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Maintenance Costs'},
        ),
        migrations.AlterField(
            model_name='billablecostitems',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='billablecostitems/photos/'),
        ),
    ]
