# Generated by Django 5.1.1 on 2025-02-12 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0104_alter_maintenancecost_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('season_start_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('season_end_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Farm Season',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_validity_date', models.DateField()),
                ('greenhouse', models.ForeignKey(blank=True, help_text='If empty, this cost applies to all greenhouses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_cost_greenhouses', to='yuapp.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='yuapp.beneficiary')),
                ('farmseason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmseasons', to='yuapp.farmseason')),
                ('maintenance_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.maintenancecosting')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('greenhouse', models.ForeignKey(blank=True, help_text='If empty, this cost applies to all greenhouses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='yuapp.greenhouse')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancecosting',
            name='cost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_cost_items', to='yuapp.maintenancecostitem'),
        ),
    ]
