# Generated by Django 5.1.1 on 2025-02-13 00:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0105_farmseason_maintenancecosting_maintenancebilling_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billablecostitems',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='billablecostitems',
            name='greenhouse',
        ),
        migrations.RemoveField(
            model_name='maintenancecost',
            name='billable_item',
        ),
        migrations.RemoveField(
            model_name='maintenancebilling',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='maintenancebilling',
            name='farmseason',
        ),
        migrations.RemoveField(
            model_name='maintenancebilling',
            name='maintenance_cost',
        ),
        migrations.RemoveField(
            model_name='maintenancecost',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='maintenancecost',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='maintenancecost',
            name='greenhouse',
        ),
        migrations.RemoveField(
            model_name='maintenancecosting',
            name='cost_item',
        ),
        migrations.RemoveField(
            model_name='maintenancecosting',
            name='greenhouse',
        ),
        migrations.RemoveField(
            model_name='maintenancecostitem',
            name='greenhouse',
        ),
        migrations.AlterModelOptions(
            name='farmseason',
            options={},
        ),
        migrations.RemoveField(
            model_name='farmseason',
            name='active',
        ),
        migrations.AlterField(
            model_name='farmseason',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmseason',
            name='season_end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='farmseason',
            name='season_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='BillableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('applies_to_all', models.BooleanField(default=False, help_text='If checked, applies to all beneficiaries')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary')),
                ('farm_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.farmseason')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary')),
            ],
        ),
        migrations.DeleteModel(
            name='BeneficiaryMaintenanceShare',
        ),
        migrations.DeleteModel(
            name='BillableCostItems',
        ),
        migrations.DeleteModel(
            name='MaintenanceBilling',
        ),
        migrations.DeleteModel(
            name='MaintenanceCost',
        ),
        migrations.DeleteModel(
            name='MaintenanceCosting',
        ),
        migrations.DeleteModel(
            name='MaintenanceCostItem',
        ),
    ]
