# Generated by Django 5.1.1 on 2025-02-13 21:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0106_remove_billablecostitems_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billableitem',
            name='applies_to_all',
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='cost',
        ),
        migrations.AddField(
            model_name='billableitem',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, accessible by all greenhouse locations'),
        ),
        migrations.AlterField(
            model_name='billableitem',
            name='greenhouse',
            field=models.ForeignKey(blank=True, help_text='If assigned, only available for this greenhouse', null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse'),
        ),
        migrations.AlterField(
            model_name='farmseason',
            name='name',
            field=models.CharField(default=False, help_text='Record your farm season', max_length=255),
        ),
        migrations.CreateModel(
            name='BillableItemCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('billable_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.billableitem')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('greenhouse', models.ForeignKey(blank=True, help_text='If assigned, applies only to this greenhouse', null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse')),
            ],
        ),
    ]
