# Generated by Django 5.1.1 on 2025-02-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0107_remove_billableitem_applies_to_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmseason',
            name='name',
            field=models.CharField(help_text='Record your farm season', max_length=255),
        ),
    ]
