# Generated by Django 5.1.1 on 2025-02-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0108_alter_farmseason_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billableitem',
            name='farmseason',
            field=models.ForeignKey(blank=True, help_text='Select a farm season in which you want this billable item be effected.', null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.farmseason'),
        ),
        migrations.AlterField(
            model_name='billableitem',
            name='name',
            field=models.CharField(help_text='Enter the name of the billable item.', max_length=255),
        ),
    ]
