# Generated by Django 5.1.1 on 2025-02-13 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0109_billableitem_farmseason_alter_billableitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billableitem',
            name='farmseason',
            field=models.ForeignKey(blank=True, help_text='Select a farm season in which you want this billable item to be effected.', null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.farmseason'),
        ),
        migrations.RemoveField(
            model_name='billableitem',
            name='greenhouse',
        ),
        migrations.AddField(
            model_name='billableitem',
            name='greenhouse',
            field=models.ManyToManyField(blank=True, help_text='Select applicable greenhouses (or leave empty if applies to all).', to='yuapp.greenhouse'),
        ),
    ]
