# Generated by Django 5.1.1 on 2025-02-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0110_alter_billableitem_farmseason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billableitemcost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
