# Generated by Django 5.1.1 on 2025-02-15 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0112_remove_servicerequest_beneficiary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequestitem',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='servicerequestitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requestitem_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
