# Generated by Django 5.1.1 on 2025-02-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0113_rename_notes_servicerequestitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='estimatedyield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
