# Generated by Django 5.1.1 on 2025-02-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0114_crop_estimatedyield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billableitem',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Billable Items'},
        ),
        migrations.AlterModelOptions(
            name='billableitemcost',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Billable Item Cost'},
        ),
        migrations.AlterModelOptions(
            name='farmseason',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Farming Cycle'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Invoice'},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Service Item'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Service Request'},
        ),
        migrations.AlterModelOptions(
            name='servicerequestitem',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Service Request Items'},
        ),
    ]
