# Generated by Django 5.1.1 on 2025-02-16 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0115_alter_billableitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Service Items'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Service Requests'},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edo_servicerequests_for_beneficiary', to='yuapp.beneficiary'),
        ),
    ]
