# Generated by Django 5.1.1 on 2025-02-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0116_alter_serviceitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='confirmed_at',
            new_name='approve_at',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='fulfilled_by',
            new_name='approve_by',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='confirmation_note',
            new_name='approve_note',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='fulfilled_at',
        ),
    ]
