# Generated by Django 5.1.1 on 2025-02-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0117_rename_confirmed_at_servicerequest_approve_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='cost_component',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Construction Cost'),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='number_of_rooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Rooms (Tunnels)'),
        ),
        migrations.AddField(
            model_name='greenhouseroom',
            name='shared_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Shared Construction Cost'),
        ),
    ]
