# Generated by Django 5.1.1 on 2025-02-25 12:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0118_greenhouse_cost_component_greenhouse_number_of_rooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuapp.supervisor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SaleAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='saleagent/photos/', verbose_name='Passport Picture')),
                ('nationalId', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Ghana Card')),
                ('cardphoto', models.ImageField(blank=True, null=True, upload_to='saleagent/photos/', verbose_name='Ghana Card Picture')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ManyToManyField(blank=True, to='yuapp.city')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleagent_created_by', to=settings.AUTH_USER_MODEL)),
                ('marketingcentre', models.ManyToManyField(blank=True, related_name='marketingcentres', to='yuapp.marketingcentre')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Marketing & Sale Agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
