# Generated by Django 5.1.1 on 2025-02-26 16:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0120_alter_saleagent_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
       
    ]
