# Generated by Django 5.1.1 on 2025-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0121_remove_order_supervisor_remove_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
