# Generated by Django 5.1.1 on 2025-02-26 21:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0122_alter_payment_amount_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='order',
            name='saleagent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_saleagent', to='yuapp.saleagent'),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='paidby',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='payments/photos/', verbose_name='Attach Evidence'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='confirmation',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Open', 'Open')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='price_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuapp.pricetable'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='status',
            field=models.CharField(default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='yuapp.order'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Balance_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='yuapp.order')),
            ],
            options={
                'verbose_name_plural': 'Purchase Payment Balances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('delivered_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='yuapp.order')),
            ],
            options={
                'verbose_name_plural': 'Purchase Order Fulfillments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HarvestMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('received', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement_createdby', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.crop')),
                ('from_market_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements_stock', to='yuapp.marketingcentre')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.grade')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement_receivedby', to=settings.AUTH_USER_MODEL)),
                ('to_market_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements_stock', to='yuapp.marketingcentre')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.productunit')),
            ],
            options={
                'verbose_name_plural': 'Harvest Movements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestStockAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aggregation_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggregate_stock_movement_createdby', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.crop')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.grade')),
                ('market_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_stock_marketcentre', to='yuapp.marketingcentre')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.productunit')),
            ],
            options={
                'verbose_name_plural': 'Harvest Stock Aggregates',
                'ordering': ['-aggregation_date'],
                'unique_together': {('market_centre', 'crop', 'grade', 'unit', 'aggregation_date')},
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('harveststock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_stock_item', to='yuapp.harveststockaggregate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='yuapp.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.orderdetail'),
        ),
    ]
