# Generated by Django 5.1.1 on 2025-02-26 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0123_remove_payment_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.orderitem'),
        ),
    ]
