# Generated by Django 5.1.1 on 2025-02-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0124_alter_delivery_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhouse',
            name='marketing_centres',
        ),
        migrations.AlterField(
            model_name='harvest',
            name='confirmation',
            field=models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='marketing_centres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.marketingcentre', verbose_name='marketcentre'),
        ),
    ]
