# Generated by Django 5.1.1 on 2025-02-28 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0125_remove_greenhouse_marketing_centres_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harveststockaggregate',
            name='active',
        ),
        migrations.RemoveField(
            model_name='harveststockaggregate',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='harveststockaggregate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='harveststockaggregate',
            name='market_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.marketingcentre'),
        ),
        migrations.RemoveField(
            model_name='saleagent',
            name='marketingcentre',
        ),
        migrations.AddField(
            model_name='saleagent',
            name='marketingcentre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketingcentre', to='yuapp.marketingcentre'),
        ),
    ]
