# Generated by Django 5.1.1 on 2025-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0126_remove_harveststockaggregate_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harveststockaggregate',
            options={'ordering': ['aggregation_date'], 'verbose_name_plural': 'Harvest Stock Aggregates'},
        ),
        migrations.AlterField(
            model_name='harveststockaggregate',
            name='aggregation_date',
            field=models.DateField(),
        ),
    ]
