# Generated by Django 5.1.1 on 2025-02-28 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0127_alter_harveststockaggregate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harveststockaggregate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
