# Generated by Django 5.1.1 on 2025-03-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0128_harveststockaggregate_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Crop Harvest Records'},
        ),
        migrations.AddField(
            model_name='harveststockaggregate',
            name='unit_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.pricetable'),
        ),
    ]
