# Generated by Django 5.1.1 on 2025-03-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0129_alter_harvest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.ManyToManyField(blank=True, to='yuapp.city'),
        ),
    ]
