# Generated by Django 5.1.1 on 2025-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0130_buyer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='reviewed_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed')], default='Open', max_length=20),
        ),
    ]
