# Generated by Django 5.1.1 on 2025-03-31 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0131_harvest_reviewed_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='reviewed_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Agree', 'Agree'), ('Disagree', 'Disagree')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crop_variety/photos/', verbose_name='Attach Picture')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_crop', to='yuapp.crop')),
            ],
            options={
                'verbose_name_plural': 'Crop Variety',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='nurserydata',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_variety', to='yuapp.cropvariety'),
        ),
    ]
