# Generated by Django 5.1.1 on 2025-03-31 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0132_alter_harvest_reviewed_status_cropvariety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurserydata',
            name='cropvariety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_variety', to='yuapp.cropvariety'),
        ),
        migrations.AlterField(
            model_name='nurserydata',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.crop'),
        ),
    ]
