# Generated by Django 5.1.1 on 2025-04-01 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0133_nurserydata_cropvariety_alter_nurserydata_crop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sprayingdata',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprayingdata',
            name='feedback_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sprayingdata',
            name='feedback_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprayingdata_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sprayingdata',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprayingdata_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
