# Generated by Django 5.1.1 on 2025-04-05 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0134_sprayingdata_feedback_sprayingdata_feedback_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='yuapp.orderitem'),
        ),
        migrations.CreateModel(
            name='Spoilage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('spoilage_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='order/spoilage/photos/', verbose_name='Attach Evidence')),
                ('notes', models.TextField(default='')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spoilage_confirmation', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spoilage_created', to=settings.AUTH_USER_MODEL)),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderspoilage', to='yuapp.orderitem')),
            ],
            options={
                'verbose_name_plural': 'Purchase Order Spoilage',
                'ordering': ['-created_at'],
            },
        ),
    ]
