# Generated by Django 5.1.1 on 2025-04-05 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0135_alter_fulfillment_order_spoilage'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='cropvariety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.cropvariety'),
        ),
    ]
