# Generated by Django 5.1.1 on 2025-04-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0136_harvest_cropvariety'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
