# Generated by Django 5.1.1 on 2025-04-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0137_harvest_review_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='harveststockaggregate',
            name='cropvariety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.cropvariety'),
        ),
    ]
