# Generated by Django 5.1.1 on 2025-04-13 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0141_pricetable_cropvariety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Purchase Order Payment'},
        ),
        migrations.AlterModelOptions(
            name='spoilage',
            options={'ordering': ['-reported_at'], 'verbose_name_plural': 'Purchase Order Spoilage'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='photo',
            new_name='receipt_image',
        ),
        migrations.RenameField(
            model_name='spoilage',
            old_name='created_at',
            new_name='confirmed_at',
        ),
        migrations.RenameField(
            model_name='spoilage',
            old_name='photo',
            new_name='photo_evidence',
        ),
        migrations.RenameField(
            model_name='spoilage',
            old_name='quantity',
            new_name='quantity_spoiled',
        ),
        migrations.RenameField(
            model_name='spoilage',
            old_name='created_by',
            new_name='reported_by',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='spoilage',
            name='confirmation_note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spoilage',
            name='reported_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
