# Generated by Django 5.1.1 on 2025-04-26 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0142_alter_payment_options_alter_spoilage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestmovement',
            name='cropvariety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.cropvariety'),
        ),
    ]
