# Generated by Django 5.1.1 on 2025-05-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0143_harvestmovement_cropvariety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harveststockaggregate',
            name='aggregation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
