# Generated by Django 5.1.1 on 2025-05-10 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0144_alter_harveststockaggregate_aggregation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('credit', 'Credit Purchase')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='harveststockaggregate',
            name='aggregation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
