# Generated by Django 5.1.1 on 2025-05-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0145_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_credit_approved',
            field=models.BooleanField(default=False),
        ),
    ]
