# Generated by Django 5.1.1 on 2025-05-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0147_remove_balance_outstanding_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/slips/', verbose_name='Attach Evidence'),
        ),
    ]
