# Generated by Django 5.1.1 on 2025-05-10 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0148_alter_payment_receipt_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='receipt_image',
            new_name='payin_slip',
        ),
    ]
