# Generated by Django 5.1.1 on 2025-05-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0150_payment_reference_number_payment_transaction_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
