# Generated by Django 5.1.1 on 2025-05-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0151_alter_payment_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Mobile/Bank Number'),
        ),
    ]
