# Generated by Django 5.1.1 on 2025-05-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0152_alter_payment_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_payments', to='yuapp.bankpayment', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method_mobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_payments', to='yuapp.mobilepayment', verbose_name='Momo Provider'),
        ),
    ]
