# Generated by Django 5.1.1 on 2025-06-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0155_alter_payment_payment_method_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='sale_order_type',
        ),
    ]
