# Generated by Django 5.1.1 on 2025-06-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0157_alter_order_sale_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale_order_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit Purchase')], default='cash', max_length=20, verbose_name='Sale Order Type'),
        ),
    ]
