# Generated by Django 5.1.1 on 2025-06-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0158_alter_order_sale_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmation_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed_by',
        ),
    ]
