# Generated by Django 5.1.1 on 2025-06-12 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0160_alter_balance_options_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Payment Balance', 'verbose_name_plural': 'Order Payment Balances'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Payment', 'verbose_name_plural': 'Order Payments'},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='yuapp_order_order_d_0f1c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='yuapp_order_status_49d6a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='amount_paid_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.CheckConstraint(condition=models.Q(('total_due__gte', 0)), name='total_due_gte_0'),
        ),
    ]
