# Generated by Django 5.1.1 on 2025-06-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0163_historicalpayment_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankpayment',
            options={'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='mobilepayment',
            options={'verbose_name_plural': 'Mobile Money'},
        ),
    ]
