# Generated by Django 5.1.1 on 2025-06-12 21:18

import django.core.validators
import yuapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0164_alter_bankpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='cardphoto',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiary/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Ghana Card Picture'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiary/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Passport Picture'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='buyer/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='changingroom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='changingroom/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Upload Photo'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='crop/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Picture'),
        ),
        migrations.AlterField(
            model_name='cropvariety',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='crop_variety/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Picture'),
        ),
        migrations.AlterField(
            model_name='farminput',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farminput/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='farminputcategory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farminput/category/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='greenhouse/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='greenhouseroom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='greenhouseroom/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='payin_slip',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Proof of Payment'),
        ),
        migrations.AlterField(
            model_name='inputdealer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farminput/dealer/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payin_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payments/slips/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Proof of Payment'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='repayment/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Evidence'),
        ),
        migrations.AlterField(
            model_name='saleagent',
            name='cardphoto',
            field=models.ImageField(blank=True, null=True, upload_to='saleagent/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Ghana Card Picture'),
        ),
        migrations.AlterField(
            model_name='saleagent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='saleagent/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Passport Photo'),
        ),
        migrations.AlterField(
            model_name='spoilage',
            name='photo_evidence',
            field=models.ImageField(blank=True, null=True, upload_to='order/spoilage/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Evidence'),
        ),
        migrations.AlterField(
            model_name='storeroom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='storeroom/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Upload Photo'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='cardphoto',
            field=models.ImageField(blank=True, null=True, upload_to='edo/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Ghana Card Picture'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='edo/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Passport Picture'),
        ),
        migrations.AlterField(
            model_name='trendknowledgebank',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trendknowledgebank/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='trendknowledgediscussion',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trendknowledgediscussion/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='watertank',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='watertanks/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='cardphoto',
            field=models.ImageField(blank=True, null=True, upload_to='worker/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Ghana Card Picture'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Passport Photo'),
        ),
    ]
