# Generated by Django 5.1.1 on 2025-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0165_alter_beneficiary_cardphoto_alter_beneficiary_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='total_items',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_items',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
