# Generated by Django 5.1.1 on 2025-06-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0166_alter_historicalorder_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'harveststock')},
        ),
    ]
