# Generated by Django 5.1.1 on 2025-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0167_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestmovement',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalharvestmovement',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
