# Generated by Django 5.1.1 on 2025-06-21 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0168_harvestmovement_quantity_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_tunnel', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seeds_sown', models.IntegerField()),
                ('seeds_germinated', models.IntegerField()),
                ('seedlings_transplanted', models.IntegerField()),
                ('last_fuel_filling_per_litre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_pecentage_level_before_run', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_pecentage_level_after_run', models.DecimalField(decimal_places=2, max_digits=5)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('finishTime', models.TimeField(blank=True, null=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, choices=[('Pwr Outage', 'Pwr Outage'), ('Test', 'Test'), ('maintenance', 'Maintenance')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tunnel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tunnel', to='yuapp.greenhouseroom')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_category', to='yuapp.maintenancecategory')),
            ],
            options={
                'verbose_name_plural': 'Maintenance',
                'ordering': ['-created_at'],
            },
        ),
    ]
