# Generated by Django 5.1.1 on 2025-06-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0169_maintenancecategory_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='seedlings_transplanted',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='seeds_germinated',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='seeds_sown',
        ),
    ]
