# Generated by Django 5.1.1 on 2025-06-29 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0170_remove_maintenance_seedlings_transplanted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipMaintenanceLogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Equipment Maintenance Log Category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Equipment Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Equipment Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Equipment Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('part_use', models.CharField(blank=True, choices=[('replaced', 'Replaced'), ('repaired', 'Repaired')], max_length=20, null=True, verbose_name='Part Usage')),
                ('status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('in-progress', 'In Progress')], max_length=20, null=True, verbose_name='Repair Status')),
                ('description', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(max_length=255, verbose_name='Approved Person')),
                ('performed_by', models.CharField(max_length=255, verbose_name='Engineer')),
                ('performed_by_phone', models.CharField(max_length=15, verbose_name='Engineer Phone')),
                ('tested_by', models.CharField(max_length=255, verbose_name='Tester')),
                ('tested_by_phone', models.CharField(max_length=15, verbose_name='Tester Phone')),
                ('test_feedback', models.CharField(choices=[('resolved', 'Resolved'), ('not resolved', 'Not Resolved')], max_length=20, verbose_name='Tester Feedback')),
                ('maintenance_duration', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maintenance Duration')),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maintenance Cost')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_category', to='yuapp.equipmaintenancelogcategory')),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_equipment', to='yuapp.equipment')),
                ('part', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_part', to='yuapp.equipmentpart')),
                ('code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_code', to='yuapp.maintenancecode')),
            ],
            options={
                'verbose_name_plural': 'Equipment Maintenance Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
