# Generated by Django 5.1.1 on 2025-06-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0171_equipmaintenancelogcategory_equipment_equipmentpart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipMaintenanceLogCategory',
            new_name='EquipmentCategory',
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Equipments'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Equipment Category'},
        ),
        migrations.AlterModelOptions(
            name='equipmentmaintenancelog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Maintenance Equipment Log'},
        ),
        migrations.AlterModelOptions(
            name='equipmentpart',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Equipment Parts'},
        ),
        migrations.AlterModelOptions(
            name='maintenancecode',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Maintenance Code'},
        ),
        migrations.RemoveField(
            model_name='equipmentmaintenancelog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equipmentmaintenancelog',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_category', to='yuapp.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='equipmentpart',
            name='equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='yuapp.equipment'),
        ),
    ]
