# Generated by Django 5.1.1 on 2025-06-29 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0172_rename_equipmaintenancelogcategory_equipmentcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_category', to='yuapp.equipmentcategory'),
        ),
    ]
