# Generated by Django 5.1.1 on 2025-06-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0173_alter_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmaintenancelog',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_code', to='yuapp.maintenancecode'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenancelog',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_part', to='yuapp.equipmentpart'),
        ),
        migrations.AlterField(
            model_name='equipmentpart',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='yuapp.equipment'),
        ),
    ]
