# Generated by Django 5.1.1 on 2025-07-18 13:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import yuapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0174_alter_equipmentmaintenancelog_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancecode',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Maintenance Code'},
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='finance/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Passport Photo')),
                ('nationalId', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Ghana Card')),
                ('cardphoto', models.ImageField(blank=True, null=True, upload_to='finance/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), yuapp.models.validate_file_size], verbose_name='Ghana Card Picture')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ManyToManyField(blank=True, to='yuapp.city')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_created_by', to=settings.AUTH_USER_MODEL)),
                ('marketingcentre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_marketingcentre', to='yuapp.marketingcentre')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Finance Team',
                'ordering': ['-created_at'],
            },
        ),
    ]
