# Generated by Django 5.1.1 on 2024-09-11 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0002_city_country_district_alter_beneficiary_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='assigned_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='yuapp.supervisor'),
        ),
        migrations.AddField(
            model_name='cashassigned',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='changingroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='changingroomassign',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='district',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='greenhouseroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeroomassign',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trendknowledgebank',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trendknowledgediscussion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watertank',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('maintenance_type', models.CharField(choices=[('watertank', 'Water Reservoir'), ('greenhouse', 'Greenhouse'), ('greenhouseroom', 'Greenhouse Room'), ('changingroom', 'Changing Room'), ('storeroom', 'Store Room')], max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changingroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.changingroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouse')),
                ('greenhouseroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.greenhouseroom')),
                ('storeroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.storeroom')),
                ('watertank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yuapp.watertank')),
            ],
            options={
                'verbose_name_plural': 'Maintenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_incurred', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.maintenance')),
            ],
            options={
                'verbose_name_plural': 'Maintenance Cost',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryMaintenanceShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.beneficiary')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maintenance_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuapp.maintenancecost')),
            ],
            options={
                'verbose_name_plural': 'Maintenance Cost Distribution',
                'ordering': ['-created_at'],
            },
        ),
    ]
