# Generated by Django 5.1.1 on 2024-09-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0004_remove_greenhouseroom_beneficiary_beneficiary_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='notes',
        ),
    ]
