# Generated by Django 5.1.1 on 2024-09-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0005_remove_crop_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Enterprise Development Officer'},
        ),
    ]
