# Generated by Django 5.1.1 on 2024-09-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0008_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/photos/', verbose_name='Attach Photo'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='repayment/photos/', verbose_name='Attach Evidence'),
        ),
        migrations.AddField(
            model_name='trendknowledgediscussion',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trendknowledgediscussion/photos/', verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiary/photos/', verbose_name='Passport Picture'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact_person',
            field=models.CharField(max_length=255, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='buyers/photos/', verbose_name='Upload Photo'),
        ),
        migrations.AlterField(
            model_name='changingroom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='changingroom/photos/', verbose_name='Upload Photo'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='crop/photos/', verbose_name='Attach Picture'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='greenhouse/photos/', verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='greenhouseroom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='greenhouseroom/photos/', verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='storeroom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='storeroom/photos/', verbose_name='Upload Photo'),
        ),
        migrations.AlterField(
            model_name='trendknowledgebank',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trendknowledgebank/photos/', verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='watertank',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='watertanks/photos/', verbose_name='Attach Photo'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker/photos/', verbose_name='Passport Picture'),
        ),
    ]
