# Generated by Django 5.1.1 on 2024-09-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0010_beneficiary_cardphoto_supervisor_cardphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker/photos/', verbose_name='Passport Picture'),
        ),
    ]
