# Generated by Django 5.1.1 on 2024-09-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0011_alter_supervisor_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greenhouseroom',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Greenhouse Rooms'},
        ),
        migrations.AlterField(
            model_name='greenhouseroom',
            name='greenhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='yuapp.greenhouse'),
        ),
    ]
