# Generated by Django 5.1.1 on 2024-09-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0013_alter_greenhouse_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcentre',
            name='city',
            field=models.ManyToManyField(blank=True, to='yuapp.city', verbose_name='Cluster/Sites'),
        ),
    ]
