# Generated by Django 5.1.1 on 2024-09-12 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuapp', '0015_changingroom_greenhouse_storeroom_greenhouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeroomassign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storeroom_assign_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storeroom',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storeroom_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
